### ISSUE TITLE
r1 TODO

### ISSUE THREAD

**Issue by MistakeNot4892** [Zuhayr/Phantasma#1]
- [x] finish item panel display
- [x] finish minion panel display
- [x] Stat readouts on the minion info panel
- [ ] Add TMs.
- [ ] Add minion capturing/storage.
- [ ] Add minion evolution code framework.
- [ ] Add level-based movesets.
- [ ] Add a random minion generator.
- [ ] Add a basic island map.
- [ ] Add a spawn area.
- [ ] Additional trainer bodies/clothes/eyes/art + world icons
- [ ] Finish the 'create new character' panel
- [ ] Add world icons and updated battle icons for minions
